name: EVM/RPC

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rpc-goerli-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17.0"
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: go test -v ./node/rpc_test.go

  rpc-meta-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17.0"
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: go test -v ./node/rpc_meta_test.go
