name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rpc-tests:
    if: ${{ github.repository == 'SKIP__ON__PURPOSE'}}
    name: RPC tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@27135e314dd1818f797af1db9dae03a9f045786b

      - uses: actions/setup-go@c51a7207680f1bee06f4a751214aab70667f9e25
        with:
          go-version: '^1.17.0'
          
      - name: Run rpc tests
        run: |
          ETHLIBS_TEST_WS_URL=${{ vars.ETHLIBS_TEST_WS_URL }} go test -v ./node/rpc_test.go

